<ul class="nav nav-tabs">
  <li role="presentation" id="home"><a href="/home.php">Office</a></li>
  <li role="presentation" id="freeagent"><a href="freeagent.php">Free Agents</a></li>
  <li role="presentation" id="stadium"><a href="#">Stadium</a></li>
  <li role="presentation" id="trading"><a href="#">Trading Block</a></li>
  <li role="presentation" id="finance"><a href="#">Finances</a></li>
</ul><br />
